### ISSUE TITLE
Redirect to a chat page

### ISSUE THREAD

**Issue by helper-uttam** [helper-uttam/ChatAndRelax#1]
- [x] Adding basic server files
- [x] after taking credentials redirect users to a specific room acc to their chosen feeling.
- [x] optimizing CSS
- [x] Adding Heroku Deployment via CI/CD

**Comment by mohanbyte** [comment]
Can i work on it is it available?

**Comment by helper-uttam** [comment]
Hello @kmohan0910 , thanks for showing your intrest in working together and add value to open source. But I'm making this project for a competition and I think they will not be counting this as a valid submission.
But no worries, please feel free to look into the opened issue after 2 days (when the competition will be over).

I'd love to work together..!
